config/routes.rb
Rails.application.routes.draw do


  root to: "posts#index"

  devise_for :users

  resources :posts do
    collection do
      patch 'search'
      get 'my_posts', as: 'my'
    end
  end

  match '/react', to: 'welcome#index', as: 'react', via: :get

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user, :title, :body
  validates_uniqueness_of :title

  # return only featured posts
  scope :featured, -> { where(featured: true).includes(:user) }
  # return only unfeatured posts
  scope :unfeatured, -> { where(featured: false).includes(:user) }
  # return user featured posts
  scope :user_featured, -> (user) { where(featured: true, user: user).includes(:user) }
  # return user unfeatured posts
  scope :user_unfeatured, -> (user) { where(featured: false, user: user).includes(:user) }

  # truncate body so we display only first 100 chars on index page
  def truncated_body
    return self.body if body.size < 100
    self.body.first(100) + '...'
  end

  # search post with field and query
  def self.search(field, query)
    where("lower(#{field}) LIKE ? AND featured IS false", "%#{query.downcase}%")
  end

  # remove featured from one post and add it to another
  def self.swap_featured
    featured = Post.featured.first
    unfeatured = Post.unfeatured.sample
    ActiveRecord::Base.transaction do
      featured.update_attributes! featured: false
      unfeatured.update_attributes! featured: true
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #  :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable, :lockable

  has_many :posts, dependent: :destroy

  validates_presence_of :name
  validates_uniqueness_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  protected

  def not_authorized
    redirect_to root_path, notice: "Can't access this page."
  end

  def devise_parameter_sanitizer
    if resource_class == User
      UserParamsSanitizer.new(User, :user, params)
    else
      super
    end
  end

end

app/controllers/concerns/user_params_sanitizer.rb
class UserParamsSanitizer < Devise::ParameterSanitizer

  def sign_up
    default_params.permit(:name, :email, :password, :password_confirmation)
  end

  def account_update
    default_params.permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_featured_post, only: [:index, :search]
  before_action :authenticate_user!, only: [:new, :my_posts, :edit, :create, :update, :destroy]
  after_action :verify_authorized

  # GET /posts
  def index
    @posts = Post.unfeatured.order(created_at: :desc).paginate(page: page, per_page: per_page)
    authorize Post
  end

  # GET /posts/my_posts
  def my_posts
    @featured_post = Post.user_featured(current_user).first
    @posts = Post.user_unfeatured(current_user).order(created_at: :desc).paginate(page: page, per_page: per_page)
    authorize Post, :index?
    respond_to do |format|
      format.html {render 'index'}
      format.json {render 'index'}
      format.xml {render 'index'}
    end
  end

  # GET /posts/search
  def search
    @posts = Post.search(:title, params[:q]).order(created_at: :desc).paginate(page: page, per_page: per_page)
    authorize Post, :index?
    respond_to do |format|
      format.html {render 'index'}
      format.json {render 'index'}
      format.xml {render 'index'}
    end
  end

  # GET /posts/1
  def show
    authorize @post
    respond_to do |format|
      format.html {}
      format.json {@post}
      format.xml {@post}
    end
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
    authorize @post
  end

  # GET /posts/1/edit
  def edit
    authorize @post
  end

  # POST /posts
  def create
    @post = current_user.posts.new(post_params)
    authorize @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        format.xml { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.xml { render xml: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
        format.xml { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.xml { render xml: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  def destroy
    authorize @post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
      format.xml { head :no_content }
    end
  end

  private

    def per_page
      if params[:per_page]
        params[:per_page].to_i < 10 ? params[:per_page].to_i : 10
      else
        9
      end
    end

    def page
      params[:page] || 1
    end

    def set_featured_post
      @featured_post = Post.featured.first
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :q)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      flash_div(msg_type, message)
    end
    nil
  end

  def errors(messages)
    messages.each do | message|
      flash_div('alert-danger', message)
    end
    nil
  end

  private

  def flash_div(msg_type, message)
    concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in", role: 'alert') do
            concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
            concat message
          end)
  end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="Test blog">
  <meta name="author" content="Sasa Sekaric">
  <link rel="icon" href="../../favicon.ico">

  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-dark bg-primary navbar-fixed-top">
      <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header">
        &#9776;
      </button>
      <div class="collapse navbar-toggleable-xs" id="navbar-header">
        <%= link_to "Blog", root_path, class: 'navbar-brand' %>
        <ul class="nav navbar-nav">
          <% if !user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Log In", new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Settings", edit_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "My Posts", my_posts_path, class: 'nav-link' %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Reactive App", react_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Create Post", new_post_path, class: 'btn btn-primary' %>
          </li>
        </ul>

        <%= form_tag(search_posts_path, method: "patch", class: 'form-inline pull-xs-right') do %>
          <%= text_field_tag :q, nil, class: 'form-control', placeholder: 'Search posts by title' %>
          <%= submit_tag "Search", class: 'btn btn-primary' %>
        <% end %>

      </div>
    </nav> <!-- /navbar -->

    <div id="yield" class="<%= params[:controller] %>-<%= params[:action] %>">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </div> <!-- /container -->
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, html: {class: 'form'}) do |f| %>
  <% if @post.errors.any? %>
    <div class="row">
      <div class="form-group col-xs-12 col-md-8 col-md-offset-2">
        <%= errors(@post.errors.full_messages) %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="form-group col-xs-12 col-md-8 col-md-offset-2">
      <%= f.label :title, class: 'sr-only' %>
      <%= f.text_field :title, autofocus: true, class: 'form-control', placeholder: 'title' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-xs-12 col-md-8 col-md-offset-2">
      <%= f.label :body, class: 'sr-only' %>
      <%= f.text_area :body, class: 'form-control', placeholder: 'Body', rows: 10 %>
    </div>
  </div>
  <%= f.submit params[:action] == 'new' ? 'Create' : 'Update', class: 'btn btn-primary' %>
<% end %>

app/views/posts/_post.html.erb
<% if (params[:action] == 'search' or params[:action] == 'index' or params[:action] == 'my_posts') && !post.featured %>
  <div class="col-sm-12 col-md-6 col-lg-4" data-post="<%= post.id %>">
<% else %>
  <div class="col-sm-12" data-post="<%= post.id %>">
<% end %>
    <div class="card text-xs-center">
      <% if post.featured %>
        <div class="card-header text-xs-center card-primary">
          Featured
        </div>
      <% end %>
      <div class="card-block text-xs-center">
        <h4 class="card-title"><%= post.title %></h4>
      </div>
      <div class="card-block">
        <% if params[:action] == 'show' %>
          <p class="card-text"><%= post.body %></p>
        <% else %>
          <p class="card-text"><%= post.truncated_body %></p>
          <%= link_to 'Read more...', post_path(post), class: 'card-link btn btn-sm btn-primary' %>
        <% end %>
        <% if user_signed_in? && policy(post).update? && !post.featured && (params[:action] == 'my_posts' or params[:action] == 'show' ) %>
          <%= link_to 'Edit', edit_post_path(post), class: 'card-link btn btn-sm btn-primary' %>
          <%= link_to 'Destroy', post_path(post), class: 'card-link btn btn-sm btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
        <% end %>
      </div>
      <div class="card-footer text-xs-center text-muted">
        created by <b><%= post.user.name %></b> <i><%= time_ago_in_words(post.created_at) %> ago</i>
      </div>
    </div>
  </div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-xs-12 text-xs-center">
    <h3>Edit post</h3>
    <br>
    <%= render 'form' %>
    <br>
    <br>
    <%= link_to '<< Back', :back %>
  </div>
</div>

app/views/posts/index.html.erb
<div class='row' class="posts">
  <%= render 'post', post: @featured_post if !@featured_post.nil? %>
  <%= render @posts if !@posts.empty? %>
  <% if params[:action] == 'search' %>
    <div class='row' >
      <div class="col-xs-12 text-xs-center">
        <%= link_to '<< Back', posts_path %>
      </div>
    </div>
  <% else %>
    <div class='row' >
      <div class="col-xs-12 text-xs-center">
        <%= will_paginate @posts %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-xs-12 text-xs-center">
    <h3>Create new post</h3>
    <br>
    <%= render 'form' %>
    <br>
    <br>
    <%= link_to '<< Back', posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
<%= render @post %>

app/views/welcome/index.html.erb
<%= react_component 'PostsContainer', {postsPath: posts_path} %>